src/math/mat.rs, src/math/numvec.rs, src/wad/name.rs
See this [breaking-change](https://github.com/rust-lang/rust/commit/3cb9fa26ef9905c00a29ea577fb55a12a91c8e7b)
=> Upgrade to latest Rust

src/game/level.rs, src/gfx/texture.rs, src/gfx/vbo.rs
Gets rid of some accumulated cruft.
=> Remove globs and other cleanup.

src/game/camera.rs, src/math/mat.rs
There was a bug in the rotation matrix since the beginning of time and I just used axis rotation multiplication instead. Finally corrected the error and use that instead.
=> Fix rotation matrix computation and use it.

src/game/cached.rs, src/game/camera.rs, src/game/level.rs, src/game/lib.rs, src/game/player.rs
Refactored caching into a separate Cell-like struct which I may end up publishing on crates separately.
=> Changed camera transform cache.

Cargo.lock, src/shaders/static.vert, src/wad/image.rs, src/wad/tex.rs
=> Fix long running off-by-one animation bug.

src/game/level.rs, src/game/player.rs, src/wad/archive.rs
Includes inertia, hitting head against ceiling and jumping.
=> Adds more dynamic player movement

src/base/lib.rs, src/game/cached.rs, src/game/camera.rs, src/game/ctrl.rs, src/game/level.rs, src/game/lib.rs, src/game/player.rs, src/gfx/error.rs, src/gfx/lib.rs, src/gfx/render.rs, src/gfx/shader.rs, src/main.rs, src/math/mat.rs, src/math/numvec.rs, src/wad/archive.rs, src/wad/error.rs, src/wad/image.rs, src/wad/level.rs, src/wad/lib.rs, src/wad/meta.rs, src/wad/tex.rs, src/wad/util.rs
* Proper error handling: gfx/error.rs and wad/error.rs. Game uses Box<Error> and still panics a bit.
* Get rid of read_utf8_file. Read::read_to_string does the job just fine.
* Fix soundness hole in cached. Recursive gets could get an immutable reference to the mutable one passed in as argument.
* More docs & tests for camera.
* Replaced some single field structs (VertexShader, FragmentShader, Program, Uniform) to tuple structs.
* Renamed many getters to just the name of the field.
* More idiomatically named Archive methods.
* More operations on matrices (addition, subtraction, multiplication on refs and by-value, equality and approx_eq) and vectors (PartialEq).
* Archive is uses a RefCell now, since its mutability is unobservable from the exterior (it reads from a file, but always seeks …
=> Big cleanup and modernization

Makefile, src/wad/name.rs
Fixes the tests in wad/name.rs . These were not in the Makefile, so I hadn't noticed they'd been failing for a while :(
=> Fixed WAD tests.

Cargo.lock
=> Updated dependencies.

src/game/game.rs
Thanks to @linguica for the heads up. Fixes #36.
=> Introduce aspect ratio correction

src/game/game.rs
#40 didn't actually do this, sorry.... Fixes #36
=> Actually introduce aspect ratio correction.

src/game/game.rs, src/game/level.rs, src/gfx/error.rs, src/gfx/scene.rs, src/gfx/vertex.rs, src/main.rs, src/wad/error.rs, src/wad/image.rs, src/wad/level.rs, src/wad/meta.rs, src/wad/name.rs, src/wad/tex.rs
Some of these were found through a kind of fuzzing: I kept randomly flipping bits in the wad file trying to find panics. The WAD parser will now do a best effort attempt to keep rendering despite all odds.
=> Improve error handling and robustness

README.md
=> Remove nightly stuff from README

src/common/lib.rs, src/game/camera.rs, src/game/ctrl.rs, src/game/game.rs, src/game/level.rs, src/game/lib.rs, src/game/lights.rs, src/game/player.rs, src/gfx/error.rs, src/gfx/lib.rs, src/gfx/scene.rs, src/gfx/vertex.rs, src/gfx/window.rs, src/main.rs, src/wad/archive.rs, src/wad/error.rs, src/wad/image.rs, src/wad/level.rs, src/wad/lib.rs, src/wad/light.rs, src/wad/meta.rs, src/wad/name.rs, src/wad/read.rs, src/wad/tex.rs, src/wad/types.rs, src/wad/util.rs, src/wad/visitor.rs
=> Run rustfmt

src/game/camera.rs, src/game/ctrl.rs, src/game/game.rs, src/main.rs, src/wad/image.rs, src/wad/level.rs, src/wad/name.rs, src/wad/tex.rs, src/wad/types.rs, src/wad/visitor.rs
This is mostly about making the code more idiomatic. Actually those were all minor things, the code base is already very nice to read. :smile:
=> fixed a good number of clippy warnings

src/gfx/platform.rs, src/shaders/sky.vert, src/shaders/sprite.vert, src/shaders/static.vert
This should still support `BUFFER_TEXTURE` and `samplerBuffer`.
=> Move shaders to 140 and GL to 3.1 on Linux

src/game/level.rs, src/wad/lib.rs, src/wad/visitor.rs
Also makes `WorldVolume` (currently responsible only for figuring out the height of the floor/ceiling but in future will be relied upon for wall collision checks and much more.
=> Add visitor BSP support.

doom.toml, src/game/game.rs, src/game/player.rs
Toggled using 'f'. Also made movement resistance framerate independent and fixed some missing sprites.
=> Add flying support.

src/game/game.rs, src/game/level.rs, src/game/lib.rs, src/game/player.rs, src/game/world.rs, src/math/contact.rs, src/math/lib.rs, src/math/sphere.rs, src/math/vector.rs, src/wad/visitor.rs
This means proper collisions: both walls & flats:
* Uses swept sphere against arbitrary triangle bsp mesh for collision detection.
* Physically accurate(-ish) player movement:
* Modelled as two spheres, one above the other, connected by a spring.
* Slowdown: combination of friction and drag.
Still plenty of hacky things. At the very least simulation params should be moved to a TOML file or something. Also, World should be decoupled from LevelVisitor and made more general.
=> Collisions!

src/gfx/window.rs
The game window looks *tiny* on HiDPI screens, so it would be nice to have ability to resize the window.
=> gfx: Allow to resize game window

src/game/level.rs, src/math/mat.rs, src/math/mod.rs, src/math/vector.rs
=> Simplify vectors to cut down on compile-time

src/game/player.rs, src/math/mat.rs, src/wad/read.rs, src/wad/tex.rs
=> Remove unused imports

Cargo.lock, Cargo.toml, src/game/ctrl.rs, src/gfx/error.rs, src/gfx/text.rs, src/main.rs, src/wad/error.rs, src/wad/meta.rs, src/wad/name.rs
=> update to newest versions of deps

src/game/level.rs, src/game/mod.rs, src/game/player.rs, src/gfx/scene.rs, src/gfx/vertex.rs, src/main.rs, src/math/mat.rs, src/wad/archive.rs, src/wad/light.rs, src/wad/name.rs, src/wad/tex.rs, src/wad/visitor.rs
=> fix all clippy warnings

assets/meta/doom.toml, game/src/level.rs, scripts/tables.py, scripts/tables.txt, wad/src/lib.rs, wad/src/meta.rs, wad/src/visitor.rs
Gets rid of hardcoding in `visitor.rs`.
=> wad: read linedefs from metadata

Cargo.lock, engine/src/entities.rs, engine/src/materials.rs, engine/src/meshes.rs, engine/src/platform.rs, engine/src/projections.rs, engine/src/renderer.rs, engine/src/shaders.rs, engine/src/text.rs, engine/src/transforms.rs, engine/src/uniforms.rs, game/src/game_shaders.rs, game/src/hud.rs, game/src/level.rs, game/src/lib.rs, game/src/player.rs, wad/src/visitor.rs
=> clippy fixes

Cargo.lock
=> update deps to fix x11-dl SIGILL

Cargo.lock, Cargo.toml, engine/Cargo.toml, engine/src/input.rs, engine_derive/Cargo.toml, game/Cargo.toml, game/src/game_shaders.rs, src/main.rs
=> deps: update all dependency versions

engine/src/errors.rs, engine/src/materials.rs, game/src/lights.rs, game/src/world.rs, wad/src/archive.rs, wad/src/meta.rs, wad/src/tex.rs, wad/src/visitor.rs
@cristicbz small linter fixes, everything compiles and works
=> linters: fix; unnecessary parentness, if/else => ?, imports
